services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: basketball-coach-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: basketball_coach_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - basketball-coach-network

  # Redis (optional - for sessions/caching)
  redis:
    image: redis:7-alpine
    container_name: basketball-coach-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - basketball-coach-network

  # Next.js Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basketball-coach-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/basketball_coach_app?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=super-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - basketball-coach-network
    volumes:
      - ./uploads:/app/uploads # For file uploads if needed
    profiles:
      - production

  # Development service (default)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: basketball-coach-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/basketball_coach_app?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=super-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - basketball-coach-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
    driver: local

networks:
  basketball-coach-network:
    driver: bridge